# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: package install
        run: |
          npm install
      - name: build webpack
        run: |
          npm run build
          echo "kimchunsick.me" > dist/CNAME
        env:
          NODE_ENV: production

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          PERSONAL_TOKEN: ${{secrets.GH_DEPLOY}}
          PUBLISH_DIR: ./dist
